{% extends 'layout.swig' %}

{% block content %}
  <div class="container">
    <div class="jumbotron">
      <h1>title.</h1>

      <p>some text information.</p>

      <p class="text-center">
        just <a href="/auth"><img src="http://steamcommunity-a.akamaihd.net/public/images/signinthroughsteam/sits_large_noborder.png" alt="sign in through steam" /></a>.
      </p>
    </div>
  </div>
{% endblock %}
